default: &default
  adapter: postgis
  encoding: unicode
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  <<: *default
  database: playground_test

development:
  <<: *default
  database: playground_development

production:
  <<: *default
  database: playground_production
